### ISSUE TITLE
How to Setup when you are not working with xml views

### ISSUE THREAD

**Issue by izeryab** [SAP-samples/ui5-typescript-helloworld#10]
I am trying to export an app to typescript but we don't have xml views because we have customize ui5 components
basically i have existing openui5 application and i am trying to use your helloworld as starting point and replace the components with mine

**Comment by akudev** [comment]
Hi @izeryab, in general for support questions places like the [OpenUI5 Slack](https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com/) or [Stackoverflow](https://stackoverflow.com/questions/tagged/sapui5?tab=Newest) are better suited than this tracker for issues in the ui5-typescript-helloworld app.

Nevertheless I am willing to provide some help, but to be honest, the description of the issue you are facing is far from clear.
