### ISSUE TITLE
Adjust tsconfig.json

### ISSUE THREAD

**Issue by tobiashofmann** [SAP-samples/ui5-typescript-helloworld#18]
At the UI5con workshop for TypeScript we came accross a TS compiler/linter error related to the types and typeRoots configuration in the file tsconfig.json.

Currently the documentation at https://github.com/SAP-samples/ui5-typescript-helloworld/blob/main/step-by-step.md states for that file and the sapui5 case:

"typeRoots": [
            "./node_modules/@types",
            "./node_modules/@sapui5/ts-types-esm"
        ],

What we did during the workshop was to adjust this to:

"typeRoots": [
            "./node_modules/@types",
        ],
        "types": [
            "@openui5/ts-types-esm"
        ]

If I remember corretly this change is going to be added to the sample ts app. In that case, the tsconfig.json provided in the readme here should be updated too.

**Comment by akudev** [comment]
Fixed, thanks for spotting!
