### ISSUE TITLE
"npm install" additional libs

### ISSUE THREAD

**Issue by mcelotti** [SAP-samples/ui5-typescript-helloworld#2]
Hi, how can I "npm install" additional libs (like rxjs, lodash etc) and use them in the project? Thanks, Marco

**Comment by DetachHead** [comment]
try following [these steps](https://github.com/ui5-community/ui5-ts-shim-showcase#readme)

**Comment by mcelotti** [comment]
Thanks @DetachHead, I'm not actively working on this so I'll just close the issue.
