### ISSUE TITLE
step by step with @sapui5/types

### ISSUE THREAD

**Issue by ash-uncover** [SAP-samples/ui5-typescript-helloworld#22]
Hi,

I can not get the step by step work while using @sapui5/types.

the tsc command will always end with an error 

```
webapp/Component.ts:1:25 - error TS2307: Cannot find module 'sap/ui/core/UIComponent' or its corresponding type declarations.
1 import UIComponent from "sap/ui/core/UIComponent";
````

Any clu how to solve that ?

note that this is working fine when using @types/openui5

**Comment by akudev** [comment]
Hard to tell without seeing what your actual code is. Apparently the type definitions are not found by the compiler. Does your code editor display the same error where UIComponent is imported or is it working fine there?
In which directory do you invoke the compiler?
In which directory is the tsconfig file and how is the dependency to the types written there?
Did you do "npm install" and has this resulted in the node_modules/@sapui5/types folder, filled with the type definitions?

**Comment by ash-uncover** [comment]
Hi,

I made a simple repo reproducing the issue : https://github.com/ash-uncover/sapui5-types-issue
on branch 'openui5' im using the "@types/openui5"
on branch 'sapui5' im using the "@sapui5/types"

the two branches only differ in package.json & tsconfig.json files.

I tried to follow the step by step, and got errors in both Component.js & tsconfig.json on the sapui5 branch only.

I have seen your answers on this issue: https://github.com/ui5-community/generator-ui5-ts-app-fcl/issues/5, tried few things but problem persisted :)

-aSH

**Comment by akudev** [comment]
Well, it works for me.
Are you sure you did `npm install` after switching branches and are the types there in `node_modules/@sapui5/types`?


![image](https://github.com/SAP-samples/ui5-typescript-helloworld/assets/4866568/45433b7e-8d2b-49eb-b15e-bdb4525dc246)

**Comment by akudev** [comment]
One more possiblity: VSCode somethmes doe not notice changes in (or adding of) the type definitions. In this case, opening the command palette and executing "TypeScript: Restart TS Server" helps. This was just needed for me when the types were there after doing "npm install", but not picked up yet.

![image](https://github.com/SAP-samples/ui5-typescript-helloworld/assets/4866568/c7adb769-275c-4f48-b923-34510ff50d03)

![image](https://github.com/SAP-samples/ui5-typescript-helloworld/assets/4866568/8c0c9703-5ae3-4389-9ec7-3cb10fe112f4)

**Comment by akudev** [comment]
No response.
