### ISSUE TITLE
.eslintrc.json is outdated

### ISSUE THREAD

**Issue by ZZzzaaKK** [SAP-samples/ui5-typescript-helloworld#25]
When following part 4 of the step-by-step guide, [Set Up a Lint Check](https://github.com/SAP-samples/ui5-typescript-helloworld/blob/main/step-by-step.md#4-set-up-a-lint-check), I'm getting the following error when running `npx eslint webapp`:

```
Oops! Something went wrong! :(

ESLint: 9.8.0

ESLint couldn't find an eslint.config.(js|mjs|cjs) file.

From ESLint v9.0.0, the default configuration file is now eslint.config.js.
If you are using a .eslintrc.* file, please follow the migration guide
to update your configuration file to the new format:

https://eslint.org/docs/latest/use/configure/migration-guide

If you still have problems after following the migration guide, please stop by
https://eslint.org/chat/help to chat with the team.
```

Running the configuration migrator in the migration guide leads to another error:

```
  0:0  error  Parsing error: "parserOptions.project" has been provided for @typescript-eslint/parser.
The file was not found in any of the provided project(s): webapp/Component.js
```

Could you update the documentation and code to take into account these changes to ESLint?

Environment information:
npm --version: 10.8.2
node --version: v22.6.0

**Comment by akudev** [comment]
Thanks, yes, we should do this. The sample code [requires ESLint 8](https://github.com/SAP-samples/ui5-typescript-helloworld/blob/main/package.json#L24), but [the instructions](https://github.com/SAP-samples/ui5-typescript-helloworld/blob/main/step-by-step.md?plain=1#L174) will now result in version 9.

**Comment by petermuessig** [comment]
@akudev - we can adopt it to version 9 - I will also adopt the templates by this week.

**Comment by petermuessig** [comment]
@ZZzzaaKK - ESLint has been updated to version 9 in the `main` and `testing` branch.
