### ISSUE TITLE
Binding variables and objects from controller.ts to view.xml

### ISSUE THREAD

**Issue by MiqueiasMaia** [SAP-samples/ui5-typescript-helloworld#4]
Hey experts.

I've started to study SAPUI5 recently and I'm using TS as default. 
My doubt is how we could bind in the xml view any property from ts controller.
I saw with i18n properties but i've tryed a lot with a variable from my controller and nothing happens.

I think it's some simple, but i really coundn't do it.
On angular we just call the value with {{property_name_from_ts_file}}, but how it works here?

**Comment by MiqueiasMaia** [comment]
I've found the solution as well!

We have to do something like that:

In App.contoller.ts:
```
import Controller from "sap/ui/core/mvc/Controller";
import AppComponent from "../Component";
import JSONModel from "sap/ui/model/json/JSONModel";

/**
 * @namespace ui5.walkthroughts.controller
 */
export default class AppController extends Controller {
	oData = {
		recipient: {
			name: 'Miqueias',
			surname: 'Maia',
			age: 0,
			address: {
				street: 'Rua dos Bobos',
				number: '123'
			}
		}
	};

	public onInit(): void {
		const oModel = new JSONModel(this.oData);
		this.getView().setModel(oModel);
	}
}
```

In App.view.xml:

```
<mvc:View controllerName="ui5.walkthroughts.controller.App" displayBlock="true" xmlns="sap.m" xmlns:mvc="sap.ui.core.mvc">

	<App id="app">
		<MessagePage title="{i18n>app_title}" text="{i18n>app_title}" icon="sap-icon://accept" id="page" description="{i18n>app_description}">
			<buttons>
				<Button text="{/recipient/name}"/> <!--We are binding the object here-->
			</buttons>
		</MessagePage>
	</App>

</mvc:View>
```

It'amazing!

**Comment by akudev** [comment]
Hi, yes, as you found out, binding in XMLViews (and binding UI elements in general) in UI5 works against models, not against arbitrary variables in the controller.
See e.g. the [Databinding tutorial](https://sapui5.hana.ondemand.com/#/topic/e5310932a71f42daa41f3a6143efca9c) or the respective steps (e.g. ["Aggregation Binding"](https://sapui5.hana.ondemand.com/#/topic/bf71375454654b44af01379a3c3a6273)) in the highly recommended ["Walkthrough" tutorial](https://sapui5.hana.ondemand.com/#/topic/3da5f4be63264db99f2e5b04c5e853db).
