### ISSUE TITLE
sourceMap configuration in tsconfig

### ISSUE THREAD

**Issue by Evotionce** [SAP-samples/ui5-typescript-helloworld#5]
Hi Andreas @akudev ,
in this example the [sourceMap configuration](https://github.com/SAP-samples/ui5-typescript-helloworld/blob/main/tsconfig.json#L7) is set to `false`. 
We would expect this value to be `true` in order to see the source map also in the browser. 
Would that be the recommended setting for production? If we develop would we need to set it to true?

Thank you :)

**Comment by akudev** [comment]
Hi @Evotionce ,
With the current settings of the project, source maps *ARE* generated (inline; changed today, see below). This is configured in the build scripts in `package.json:
```json
"build:ts": "babel src --out-dir webapp --source-maps inline --extensions \".ts,.js\" --copy-files",
"watch:ts": "babel src --out-dir webapp --source-maps inline --extensions \".ts,.js\" --copy-files --watch",
```
These settings are for the  `@babel/preset-typescript` Babel plugin which actually does the transpilation.

When you just run the pure TypeScript transpiler by executing "npx tsc", then the compilation result will go straight to the "dist" directory (as specified in tsconfig) and indeed NOT contain any sourceMaps. Changing the setting to "true" in tsconfig will cause sourcemaps to be created in separate files.

In general, describing all TypeScript settings is beyond the scope of what we can do in this sample project, so whatever is not described, should be read in the respective documentation of the used tools and used "as appropriate". 

But I have used the opportunity to change the sourcemap handling to let them go to separate files (soure-maps: true) and to describe them better in the documentation (all in https://github.com/SAP-samples/ui5-typescript-helloworld/commit/9a045820fd41d65a70191c8a986e9380785077a2).

Thanks and regards
Andreas
